# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  before_all do
      ENV["FIREBASE_LOGIN_CREDENTIALS"] = "./groovy-dev-1bd09d876d85.json"
      ENV["FIREBASE_APP_ID"] = "1:44345799365:android:691bae807db84eb86036ac"
    end

  ######## FIREBASE DISTRIBUTION  ########
    desc "Submit a new Google Test Build to Firebase App Distribution"
    lane :qaRelease do |options|
       gradle(task: "clean")
       gradle(task: "assemble", flavor: "dev", build_type: "Debug")

        # find apk path
       output_path = "./app/build/outputs/apk/dev/debug/"
       output_json_path = output_path + "output-metadata.json"
       build_output = load_json(json_path: output_json_path)
       elements = build_output["elements"][0]
       apk_path = output_path + elements["outputFile"]

       release_note_information = " BRANCH => #{git_branch} - developer: #{last_git_commit[:author]}"
       release_note = "#{release_note_information} \n #{options[:r]}"

       firebase_app_distribution(
             app: ENV["FIREBASE_APP_ID"],
             apk_path: apk_path,
             release_notes: "#{release_note}",
             groups_file: "fastlane/groups.txt"
       )
       # fastlane testGoogle r:"First Alpha Release"
   end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
